CREATE TYPE PERSONA AS OBJECT (
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(30),
    APELLIDOS VARCHAR2(50),
    FECHANACIMIENTO DATE,
    MEMBER FUNCTION MUESTRAEDAD RETURN NUMBER
);
/

CREATE TYPE BODY PERSONA AS
    MEMBER FUNCTION MUESTRAEDAD RETURN NUMBER IS
        EDAD NUMBER;
    BEGIN
        EDAD := SYSDATE-FECHANACIMIENTO;
        RETURN EDAD;
    END MUESTRAEDAD;
END;
/
