DECLARE
    NOMBRE_1 OBJ_NOMBRE := OBJ_NOMBRE('Ángela','Negro','Castilla');
    DOM_1 OBJ_DOMICILIO := OBJ_DOMICILIO('Avenida','Postigo',100,'1ºA');
    CP_1 OBJ_COD_POSTAL := OBJ_COD_POSTAL(001,41);
    DATOS_1 OBJ_DATOS_PERSONALES := OBJ_DATOS_PERSONALES('A5', NOMBRE_1, DOM_1, CP_1, '18/04/1991');
    NOMBRE_2 OBJ_NOMBRE := OBJ_NOMBRE('Tom','Oxley');
    DOM_2 OBJ_DOMICILIO := OBJ_DOMICILIO('Calle','Salado',114,'21oIzq Bloque 2');
    CP_2 OBJ_COD_POSTAL := OBJ_COD_POSTAL(001,28);
    DATOS_2 OBJ_DATOS_PERSONALES := OBJ_DATOS_PERSONALES('A6', NOMBRE_2, DOM_2, CP_2, '30/05/1983');
BEGIN
    DBMS_OUTPUT.PUT_LINE(DATOS_1.DOMICILIO.TIPO_VIA);
END;
/

--Modificar
