SET SERVEROUTPUT ON;

--BLOQUE DE POLICIAS

DECLARE
    V_POLICIA1 POLICIA;
    V_POLICIA2 POLICIA;
    V_POLICIA3 POLICIA;
    salariofinal NUMBER;
    salario NUMBER;
BEGIN
    V_POLICIA1 := NEW POLICIA('12345678V','FRANCISCO','GUTIERREZ','GEIROS',123,'NACIONAL',1500);
    V_POLICIA2 := NEW POLICIA('12431234Z','MARIO','RODRIGUEZ','ALAMEDA',937,'OPERACIONES ESPECIALES',3500);
    V_POLICIA3:= NEW POLICIA('84451234G','OBERTO','RODRIGUEZ','MADRID',826,'LOCAL',1250);
    
    DBMS_OUTPUT.PUT_LINE(V_POLICIA1.telefono);
    DBMS_OUTPUT.PUT_LINE(V_POLICIA3.nombre);
    DBMS_OUTPUT.PUT_LINE('SU NUMERO DE TELEFONO ES '||V_POLICIA2.telefono||' Y SU DNI ES: '||V_POLICIA2.DNI);
    
    insert into POLICIAS values(V_POLICIA1);
    insert into POLICIAS values(V_POLICIA2);
    insert into POLICIAS values(V_POLICIA3);
    commit;
    
    update salarioBase set salarioBase=V_POLICIA1.calcularSalario() where dni=V_POLICIA1.dni;
    update salarioBase set salarioBase=V_POLICIA2.calcularSalario() where dni=V_POLICIA2.dni;
    update salarioBase set salarioBase=V_POLICIA3.calcularSalario() where dni=V_POLICIA3.dni;
END;
/
--BLOQUE DE INSPECTORES
 DECLARE
    V_INSPECTOR1 INSPECTOR;
    V_INSPECTOR2 INSPECTOR;
    V_INSPECTOR3 INSPECTOR;
BEGIN
    V_INSPECTOR1 := NEW INSPECTOR('71756287J','Enriquez','GUTIERREZ','GEIROS',123,'FORENSE');
    V_INSPECTOR2 := NEW INSPECTOR('58848006E','Alberto','RODRIGUEZ','ALAMEDA',937,'OPE');
    V_INSPECTOR3:= NEW INSPECTOR('15473116G','OBERTO','RODRIGUEZ','MADRID',826,'ADMINISTRACCION');
    
    DBMS_OUTPUT.PUT_LINE(V_INSPECTOR1.nombre);
    DBMS_OUTPUT.PUT_LINE(V_INSPECTOR3.especialidad);
    DBMS_OUTPUT.PUT_LINE(V_INSPECTOR2.dni);
    
    INSERT INTO INSPECTORES VALUES(V_INSPECTOR1);
    INSERT INTO INSPECTORES VALUES(v_inspector2);
    INSERT INTO INSPECTORES VALUES(V_INSPECTOR3);
    COMMIT;
END;
/
 